<?xml version="1.0"?>

<package format="3">

  <name>irsl_cnoid_plugin</name>
  <version>0.0.0</version>
  <description>
    Plugin for choreonoid using with irsl_choreonoid
  </description>
  <maintainer email="faculty@irsl.eiiris.tut.ac.jp"> IRSL at Toyohashi Tech </maintainer>
  <license>MIT</license>

  <url type="website">http://github.com/IRSL-tut/</url>
  <url type="repository">http://github.com/IRSL-tut/irsl_cnoid_plugin/</url>
  <url type="bugtracker">http://github.com/IRSL-tut/irsl_cnoid_plugin/issues</url>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend>choreonoid</depend>

  <export>
    <build_type>cmake</build_type>
  </export>

</package>
